package com.migc.budgetchallenge.ui.theme

import androidx.compose.ui.unit.dp

val ICON_SIZE = 48.dp
val ICON_PADDING = 8.dp
val MEDIUM_HORIZONTAL_PADDING = 8.dp
val SMALL_VERTICAL_PADDING = 4.dp
val LARGE_VERTICAL_PADDING = 12.dp
val PROGRESS_BAR_HEIGHT = 6.dp
val HOME_CARD_ROUND_CORNER = 20.dp
val HOME_CARD_VERTICAL_PADDING = 16.dp
val HOME_CARD_ELEVATION = 2.dp

val TRACKER_HEADER_PADDING = 12.dp
val TRACKER_TOP_SPACER = 24.dp
val TRACK_BAR_ROUND_CORNER = 16.dp
val TRACK_BAR_HEIGHT = 64.dp

val DIALOG_ROUND_CORNER = 16.dp
val DIALOG_TEXT_FIELD_FRAME_HEIGHT = 72.dp
val TEXT_FIELD_WIDTH = 96.dp
val TEXT_FIELD_HEIGHT = 54.dp
val CHIP_ROUND_CORNER = 18.dp
val CHIP_HORIZONTAL_PADDING = 12.dp
val CHIP_VERTICAL_PADDING = 6.dp
val CHIP_PADDING = 4.dp
val DIALOG_BUTTON_HEIGHT = 54.dp
val DIALOG_BUTTON_WIDTH = 128.dp